head.load("js/lib/jquery.js", 
					"js/lib/jquery.form-validator.min.js",
					"js/lib/flipcounter.js",
					"js/lib/jquery.fancybox.js",
					"js/lib/jquery.fancybox.pack.js",
					"js/lib/jquery.fancybox-media.js",
					"js/lib/infobox.js",
					"js/lib/infobox_packed.js",
					"js/common.js");
